-- EduTrack database setup and seed data.
-- This script can be rerun to restore the assignment's starting state.

DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;

CREATE TABLE students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    signup_date DATE NOT NULL
);

CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL,
    instructor_name VARCHAR(100),
    monthly_fee NUMERIC(10, 2) NOT NULL
);

CREATE TABLE enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    course_id INTEGER NOT NULL REFERENCES courses(id),
    enrollment_date DATE NOT NULL,
    completion_percentage INTEGER NOT NULL DEFAULT 0
        CHECK (completion_percentage BETWEEN 0 AND 100),
    passed BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_fee_paid NUMERIC(10, 2) NOT NULL
);

INSERT INTO students (id, name, email, signup_date) VALUES
    (1, 'Emily Watson', 'emily.watson@student.edutrack.com', '2024-01-10'),
    (2, 'Klaus Weber', 'klaus.weber@student.edutrack.com', '2024-02-05'),
    (3, 'Lucia Fernandes', 'lucia.fernandes@test.com', '2024-03-12'),
    (4, 'Marco Rossi', 'marco.rossi@student.edutrack.com', '2024-04-08'),
    (5, 'Yuki Nakamura', 'yuki.nakamura@test.com', '2024-05-16'),
    (6, 'Pierre Dubois', 'pierre.dubois@test.com', '2024-06-21'),
    (7, 'Priya Sharma', 'priya.sharma@student.edutrack.com', '2024-07-14'),
    (8, 'Giulia Romano', 'giulia.romano@student.edutrack.com', '2025-01-03');

INSERT INTO courses
    (id, title, category, instructor_name, monthly_fee)
VALUES
    (1, 'Intro to Python', 'Programming', 'Marta López', 49.99),
    (2, 'Web Design Basics', 'Design', 'Carlos Vega', 39.99),
    (3, 'Data Analysis with SQL', 'Data', 'Carlos Vega', 59.99),
    (4, 'Digital Marketing 101', 'Marketing', 'Lucia Prades', 29.99),
    (5, 'Advanced Python', 'Programming', 'Marta López', 69.99),
    (6, 'UI/UX Fundamentals', 'Design', NULL, 44.99),
    (7, 'Email Campaigns', 'Marketing', NULL, 34.99);

INSERT INTO enrollments
    (
        id,
        student_id,
        course_id,
        enrollment_date,
        completion_percentage,
        passed,
        monthly_fee_paid
    )
VALUES
    (1, 1, 1, '2024-03-01', 85, TRUE, 49.99),
    (2, 1, 2, '2024-04-15', 60, FALSE, 39.99),
    (3, 2, 1, '2024-03-20', 92, TRUE, 49.99),
    (4, 2, 3, '2024-05-01', 78, TRUE, 59.99),
    (5, 3, 2, '2024-06-20', 5, FALSE, 39.99),
    (6, 3, 4, '2024-07-01', 3, FALSE, 29.99),
    (7, 4, 5, '2024-03-25', 95, TRUE, 69.99),
    (8, 4, 1, '2024-08-09', 88, TRUE, 49.99),
    (9, 5, 3, '2024-09-03', 45, FALSE, 59.99),
    (10, 5, 6, '2024-10-11', 0, FALSE, 44.99),
    (11, 6, 6, '2024-11-05', 0, FALSE, 44.99),
    (12, 7, 4, '2024-12-01', 70, TRUE, 29.99),
    (13, 7, 1, '2025-01-10', 55, FALSE, 49.99),
    (14, 6, 3, '2025-02-20', 20, FALSE, 59.99),
    (15, 1, 5, '2025-03-05', 40, FALSE, 69.99);

SELECT setval(pg_get_serial_sequence('students', 'id'), 8, TRUE);
SELECT setval(pg_get_serial_sequence('courses', 'id'), 7, TRUE);
SELECT setval(pg_get_serial_sequence('enrollments', 'id'), 15, TRUE);

-- Missing enrollment to add in query 6:
-- Student: Lucia Fernandes (lucia.fernandes@test.com)
-- Course: Advanced Python
-- Enrollment date: 2025-04-01
-- Initial completion: 0
-- Passed: false
-- Monthly fee paid: 69.99
